services:
  - postgresql

language: node_js

env:
    - CONFIGPATH=config.travis.js

node_js:
    - "6"


before_script:
    - psql -c 'create database test;' -U postgres
    - psql -d test -f db.dump